#ifndef GUARD_CONSTANTS_FOLLOWER_HELPER_H
#define GUARD_CONSTANTS_FOLLOWER_HELPER_H

#define FOLLOWER_EMOTION_HAPPY 0
#define FOLLOWER_EMOTION_NEUTRAL 1 // Also called "No emotion"
#define FOLLOWER_EMOTION_SAD 2
#define FOLLOWER_EMOTION_UPSET 3
#define FOLLOWER_EMOTION_ANGRY 4
#define FOLLOWER_EMOTION_PENSIVE 5
#define FOLLOWER_EMOTION_LOVE 6
#define FOLLOWER_EMOTION_SURPRISE 7
#define FOLLOWER_EMOTION_CURIOUS 8
#define FOLLOWER_EMOTION_MUSIC 9
#define FOLLOWER_EMOTION_POISONED 10
#define FOLLOWER_EMOTION_LENGTH 11

#endif