gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "However I have a feeling you are\n"
	.string "already familiar with all of this,\l"
	.string "so I won't waste your time explaining.\p"
	.string "That just leaves me wondering...\p"
	.string "Who exactly are you?\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Ah, so you are a girl freshly\n"
	.string "moving into the HOENN Region.\p"
	.string "You've come here at an exciting time!\p"
	.string "HOENN's nature has gone through a lot\n"
	.string "of changes recently... but I'll leave\l"
	.string "those for you to discover yourself.\p"
	.string "All right. Last question!\n"
	.string "What's your name?$"

gText_Birch_BoyOrGirl::
	.string "Ah, so you are a trainer freshly\n"
	.string "moving into the HOENN Region.$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
